param([switch]$Live)
$ErrorActionPreference='Stop'
$source=[IO.File]::ReadAllText((Join-Path $PSScriptRoot '../src-tauri/resources/network/speed.cs'),[Text.Encoding]::UTF8)
Add-Type -TypeDefinition $source -ReferencedAssemblies 'System.Net.Http','System','System.Core'
function Assert([bool]$ok,[string]$message) { if(!$ok){throw $message} }
Assert ([WinEaseSpeed]::Rate(1250000,1) -eq 10) 'Mbps must use decimal bits, not MiB/s'
Assert ([WinEaseSpeed]::Rate(1,0) -eq 0) 'Zero duration must not yield Infinity'
if($Live) {
 # Explicit, bounded smoke: 128 KiB in each direction, not a full bandwidth run.
 foreach($mode in @('download','upload')) {
  $endpoint=if($mode -eq 'download'){'__down'}else{'__up'}
  $result=[WinEaseSpeed]::Run($mode,('https://speed.cloudflare.com/'+$endpoint),131072,8000,1,$true)
  $result | ConvertTo-Json -Compress
  Assert ($null -ne $result.mbps -and $result.bytes -eq 131072) ($mode+' API did not complete its payload')
 }
 exit
}
# An isolated loopback HTTP fixture serves only generated bytes, never files or live network settings.
$fixture=@'
using System;
using System.IO;
using System.Net;
using System.Net.Sockets;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
public sealed class SpeedFixture : IDisposable {
    TcpListener listener;
    public string url;
    public bool fail, compressed;
    public long uploaded, downloaded;
    public SpeedFixture() {
        listener = new TcpListener(IPAddress.Loopback, 0); listener.Start();
        url = "http://127.0.0.1:" + ((IPEndPoint)listener.LocalEndpoint).Port + "/measure";
        Task.Run(() => {
            while (true) {
                try { var client = listener.AcceptTcpClient(); Task.Run(() => Serve(client)); }
                catch { break; }
            }
        });
    }
    void Serve(TcpClient client) {
        try { using(client) using(var stream=client.GetStream()) {
            var headers = new StringBuilder(); int last=0, b;
            while((b=stream.ReadByte())>=0) {
                headers.Append((char)b);
                if(headers.Length>32768) return;
                if(b==10 && last==13 && headers.ToString().EndsWith("\r\n\r\n")) break;
                last=b;
            }
            var lines=headers.ToString().Split(new[]{"\r\n"},StringSplitOptions.None);
            bool post=lines[0].StartsWith("POST"); int length=0;
            foreach(var line in lines) if(line.StartsWith("Content-Length:",StringComparison.OrdinalIgnoreCase)) length=int.Parse(line.Substring(15).Trim());
            var buffer=new byte[65536]; int remaining=length;
            while(remaining>0) { int read=stream.Read(buffer,0,Math.Min(buffer.Length,remaining)); if(read==0) return; remaining-=read; Interlocked.Add(ref uploaded,read); }
            int size=post?0:int.Parse(lines[0].Split(new[]{"bytes="},StringSplitOptions.None)[1].Split('&',' ')[0]);
            var response=Encoding.ASCII.GetBytes("HTTP/1.1 "+(fail?"503 Unavailable":"200 OK")+"\r\nContent-Length: "+(fail?0:size)+"\r\n"+(compressed?"Content-Encoding: gzip\r\n":"")+"Connection: close\r\n\r\n");
            stream.Write(response,0,response.Length);
            if(!fail) while(size>0) { int block=Math.Min(size,buffer.Length); stream.Write(buffer,0,block); size-=block; Interlocked.Add(ref downloaded,block); }
        }} catch { }
    }
    public void Dispose() { listener.Stop(); }
}
'@
Add-Type -TypeDefinition $fixture -ReferencedAssemblies 'System','System.Core'
$server=[SpeedFixture]::new()
try {
 $down=[WinEaseSpeed]::Run('download',$server.url,524288,8000,4,$false)
 Assert ($down.bytes -eq 524288 -and $down.requestedBytes -le 524288 -and $down.mbps -gt 0) 'Download must count actual bytes and obey cap'
 $up=[WinEaseSpeed]::Run('upload',$server.url,524288,8000,4,$false)
 Assert ($up.bytes -eq 524288 -and $server.uploaded -eq 524288 -and $up.requestedBytes -le 524288 -and $up.mbps -gt 0) 'Upload must be acknowledged and obey cap'
 $latency=[WinEaseSpeed]::Run('latency',$server.url,0,8000,1,$false)
 Assert ($latency.completedRequests -eq 3 -and $null -ne $latency.latencyMs -and $null -ne $latency.jitterMs) 'Latency warmup and jitter samples'
 $server.fail=$true
 $failure=[WinEaseSpeed]::Run('download',$server.url,262144,8000,4,$false)
 Assert ($null -eq $failure.mbps -and $failure.bytes -eq 0 -and $failure.error) 'HTTP failure must not become zero Mbps'
 $server.fail=$false;$server.compressed=$true
 $invalid=[WinEaseSpeed]::Run('download',$server.url,262144,8000,4,$false)
 Assert ($null -eq $invalid.mbps -and $invalid.bytes -eq 0) 'Compressed responses must not inflate measured bytes'
 Write-Output '7 speed measurement cases passed (loopback fixtures; no live configuration changes).'
} finally {$server.Dispose()}
